services:
  - type: web
    name: geosalud-demo
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
